x = int (input ('Enter any integer less than 256: '))
y = int (input ('Enter any integer less than 256: '))
print (f'Bitwise and of x & y is:', x & y)
print (f'Bitwise or of x & y is:', x | y)
print (f'Bitwise and of x ^ y is:', x ^ y)
