print('Previos month budget')
milk=float(input('enter the budget of milk'))
sugar=float(input('enter the budget of sugar'))
tea=float(input('enter the budget of tea'))
biscuits=float(input('enter the budget of biscuits'))
print('Milk; ',milk)
print('sugar: ',sugar)
print('tea: ',tea)
print('biscuits: ',biscuits)
total=0.2*(milk+sugar+tea+biscuits)
print('next month budget')
print('Milk; ',(0.2*milk)+milk)
print('sugar: ',(0.2*sugar)+sugar)
print('tea: ',(0.2*tea)+tea)
print('biscuits: ',(0.2*biscuits)+biscuits)
print('------------------------')
print('Total:     ',total+milk+sugar+tea+biscuits)
