print('\t       *')
print('            *     *')
print('          *         *       ')
print('        **************')
print('      *                *')
print('    *                     *')
print('  *                          *')
