eng=int(input('enter your english number'))
urd=int(input('enter your urdu number'))
math=int(input('enter your maths number'))
isl=int(input('enter your islamiyat number'))
pak_st=int(input('enter your pak-study number'))
phy=int(input('enter your physics number'))
chem=int(input('enter your chemistry number'))
bio=int(input('enter your biology number'))
total=eng+urd+math+isl+pak_st+phy+chem+bio
percent=(total/525)*100
print('Subject\t\tTotal\tObtained')
print('1.English\t75\t',eng)
print('2.Urdu\t\t75\t',urd)
print('3.Maths\t\t75\t',math)
print('4.islamiyat\t50\t',isl)
print('5.Pak studies\t50\t',pak_st)
print('6.Physics\t75\t',phy)
print('7.Chemistry\t75\t',chem)
print('8.Biology\t75\t',bio)
print('Total\t\t525\t',total)
print('Percentage marks:',percent)
